donate_link: &donate_link https://giving.mit.edu/form/?fundId=3892696&amount=1000
donations_amount: 358,337
donations_account_balance: 307,337
donations_goal: 500000
number_donors: 204
menu:
  - title: Camelot Bunkhouse
    href: /camelot
  # - title: History
  #   href: /camelot/history
  - title: Project Details
    href: /camelot/project
  - title: FAQs
    href: /camelot/faqs
  - title: Donate
    href: *donate_link
